# Generated by Django 5.2.11 on 2026-02-17 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elo',
            fields=[
                ('elo_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=800)),
            ],
        ),
        migrations.CreateModel(
            name='GameInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField()),
                ('ended', models.DateTimeField()),
            ],
            options={
                'ordering': ['started'],
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_created', models.DateTimeField()),
                ('last_online', models.DateTimeField()),
                ('elo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_elo', to='chessapp.elo')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('source_location', models.CharField(max_length=2)),
                ('destination_location', models.CharField(blank=True, max_length=2, null=True)),
                ('game_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessapp.gameinstance')),
                ('piece_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessapp.piece')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessapp.player')),
            ],
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='black',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameinstance_player_black', to='chessapp.player'),
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='white',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameinstance_player_white', to='chessapp.player'),
        ),
        migrations.AddField(
            model_name='elo',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_player_id', to='chessapp.player'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.CharField(blank=True, choices=[('w', 'Win'), ('l', 'Lose'), ('d', 'Draw')], default='w', help_text='Game Result', max_length=1)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessapp.player')),
            ],
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessapp.result'),
        ),
        migrations.CreateModel(
            name='TimeControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(choices=[(5, '5 minutes'), (10, '10 minutes'), (15, '15 minutes'), (30, '30 minutes')], default=5, help_text='Time Control in minutes')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessapp.player')),
            ],
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='time_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessapp.timecontrol'),
        ),
        migrations.AddField(
            model_name='elo',
            name='time_control_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessapp.timecontrol'),
        ),
    ]
