# Generated by Django 5.2.11 on 2026-02-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timecontrol',
            name='player_id',
        ),
    ]
