# Generated by Django 5.2.11 on 2026-02-17 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0002_remove_timecontrol_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='elo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_elo', to='chessapp.elo'),
        ),
    ]
