# Generated by Django 5.2.11 on 2026-02-17 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0003_alter_player_elo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='elo',
        ),
        migrations.AlterField(
            model_name='gameinstance',
            name='time_control',
            field=models.IntegerField(choices=[(5, '5 minutes'), (10, '10 minutes'), (15, '15 minutes'), (30, '30 minutes')], default=5, help_text='Time Control in minutes'),
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_5_min', models.IntegerField(default=800)),
                ('rating_10_min', models.IntegerField(default=800)),
                ('rating_15_min', models.IntegerField(default=800)),
                ('rating_30_min', models.IntegerField(default=800)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='chessapp.player')),
            ],
        ),
        migrations.DeleteModel(
            name='Elo',
        ),
        migrations.DeleteModel(
            name='TimeControl',
        ),
    ]
